version: 2

aliases:
  - &restore-cache
    restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
        name: Install dependencies
        command: yarn --frozen-lockfile
  - &build-packages
    run:
        name: Build
        command: yarn build

jobs:
  build:
    working_directory: ~/nest
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: yarn build    

  integration_tests:
    working_directory: ~/nest
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - run:
          name: Integration tests
          command: yarn test:integration

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - integration_tests:
          requires:
            - build
      